services:
  teamspeak:
    image: teamspeak:latest
    container_name: teamspeak
    restart: always
    ports:
      - 9987:9987/udp    # voice
      - 10011:10011      # ServerQuery
      - 30033:30033      # file transfer
    environment:
      - TS3SERVER_LICENSE=accept
    volumes:
      - ./data:/var/ts3server
