services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    devices:
      - /dev/dri:/dev/dri    # GPU passthrough for hardware transcoding
    group_add:
      - "993"                # render group — required for DRI access
    volumes:
      - ./config:/config
      - /home/maximo/docker/arr-stack/media/tv:/data/tv
      - /home/maximo/docker/arr-stack/media/movies:/data/movies
    ports:
      - 8096:8096
