services:
  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr
    restart: always
    volumes:
      - ./appdata:/appdata
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 7575:7575
    environment:
      - SECRET_ENCRYPTION_KEY=${HOMARR_SECRET_KEY}    # set in .env
